[package]
authors = ["seonglae <sungle3737@gmail.com>"]
description = "A sample project with wasm-pack"
edition = "2018"
license = "MIT"
name = "hello-wasm"
repository = "https://github.com/sungle3737/hello-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
