[package]
authors = ["seonglae <sungle3737@gmail.com>"]
edition = "2018"
name = "hello-wasm"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
